"""ORM models. Importing this package registers every mapper."""

from app.models.analysis import JobAnalysis
from app.models.direction_analysis import ResumeDirectionAnalysis
from app.models.enums import (
    BenefitKey,
    CLOSED_SEARCH_TASK_RUN_STATUSES,
    DealBreakerKind,
    DealBreakerResult,
    DecisionDimension,
    ConversationStatus,
    Currency,
    DeclineReason,
    EmploymentType,
    EquityType,
    EventType,
    FeedbackTag,
    InterviewFailureReason,
    InterviewLocationType,
    InterviewOutcome,
    InterviewProcessStatus,
    InterviewRoundStatus,
    InterviewRoundType,
    OfferStatus,
    RemotePolicy,
    RevisionSource,
    RevisionType,
    JobSourceName,
    JobStatus,
    MessageDirection,
    OrchestrationEventType,
    RecommendationDecision,
    RecruiterSource,
    ResumeUsage,
    SearchTaskRunStatus,
    StrategyChangeSource,
    SupervisedSessionEventType,
    SupervisedSessionStatus,
    TaskMode,
    Verdict,
    WithdrawReason,
)
from app.models.decision import (
    DecisionProfile,
    DecisionSnapshot,
    OfferAssessment,
)
from app.models.event import ApplicationEvent
from app.models.interview import (
    ROUND_TYPE_LABEL,
    InterviewProcess,
    InterviewRound,
)
from app.models.job import Job
from app.models.offer import (
    DECLINE_REASON_LABEL,
    OFFER_STATUS_LABEL,
    REVISION_TYPE_LABEL,
    Offer,
    OfferRevision,
)
from app.models.orchestration_event import OrchestrationEvent
from app.models.recruiter import (
    RecruiterConversation,
    RecruiterMessage,
    RecruiterMessageAnalysis,
)
from app.models.resume import Resume
from app.models.application_approval import ApplicationApproval
from app.models.salary_backfill import SalaryBackfillItem, SalaryBackfillRun
from app.models.strategy import (
    CareerStrategyChange,
    StrategyRecommendationDecision,
)
from app.models.supervised_session import SupervisedSession, SupervisedSessionEvent
from app.models.task import JobSearchTask, TaskCandidate

__all__ = [
    "OfferAssessment",
    "DecisionSnapshot",
    "DecisionProfile",
    "DecisionDimension",
    "DealBreakerResult",
    "DealBreakerKind",
    "RevisionType",
    "RevisionSource",
    "RemotePolicy",
    "REVISION_TYPE_LABEL",
    "OfferStatus",
    "OfferRevision",
    "Offer",
    "OFFER_STATUS_LABEL",
    "EquityType",
    "EmploymentType",
    "DeclineReason",
    "DECLINE_REASON_LABEL",
    "Currency",
    "BenefitKey",
    "WithdrawReason",
    "ROUND_TYPE_LABEL",
    "InterviewRoundType",
    "InterviewRoundStatus",
    "InterviewRound",
    "InterviewProcessStatus",
    "InterviewProcess",
    "InterviewOutcome",
    "InterviewLocationType",
    "InterviewFailureReason",
    "FeedbackTag",
    "ApplicationEvent",
    "CareerStrategyChange",
    "ConversationStatus",
    "EventType",
    "Job",
    "JobAnalysis",
    "ResumeDirectionAnalysis",
    "JobSourceName",
    "JobStatus",
    "MessageDirection",
    "OrchestrationEvent",
    "OrchestrationEventType",
    "RecruiterConversation",
    "RecruiterMessage",
    "RecommendationDecision",
    "RecruiterMessageAnalysis",
    "RecruiterSource",
    "Resume",
    "ApplicationApproval",
    "SalaryBackfillItem",
    "SalaryBackfillRun",
    "ResumeUsage",
    "StrategyChangeSource",
    "StrategyRecommendationDecision",
    "SupervisedSession",
    "SupervisedSessionEvent",
    "SupervisedSessionEventType",
    "SupervisedSessionStatus",
    "SearchTaskRunStatus",
    "CLOSED_SEARCH_TASK_RUN_STATUSES",
    "JobSearchTask",
    "TaskCandidate",
    "TaskMode",
    "Verdict",
]
